import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const screens=['welcome','setup','dna','home','create','upload','analysis','story','instructions','draft','edit','package','publish','insights'];
function App(){
 const [s,setS]=useState('welcome'); const [name,setName]=useState('Riyaz'); const [niche,setNiche]=useState('Motorcycle'); const [style,setStyle]=useState('Cinematic, natural, emotional'); const [file,setFile]=useState(null); const [msg,setMsg]=useState('');
 const go=x=>{setMsg('');setS(x)};
 const nav=<div className="nav"><button onClick={()=>go('home')}>⌂<span>Home</span></button><button onClick={()=>go('create')}>＋<span>Create</span></button><button onClick={()=>go('insights')}>◔<span>Insights</span></button><button onClick={()=>go('dna')}>◯<span>Profile</span></button></div>;
 const Btn=({children,onClick,secondary=false})=><button className={secondary?'btn secondary':'btn'} onClick={onClick}>{children}</button>;
 if(s==='welcome')return <main className="welcome"><div className="orb">✦</div><p className="eyebrow">CREATOR COPILOT</p><h1>Create better.<br/><em>Create consistently.</em></h1><p className="muted">Your AI creative partner for turning ideas, footage and experience into content that feels like you.</p><div className="stack"><Btn onClick={()=>go('setup')}>Start testing →</Btn><Btn secondary onClick={()=>go('home')}>Explore demo</Btn></div><small>Prototype v0.1 • AI processing simulated</small></main>;
 if(s==='setup')return <Page title="Let's set up your creator profile" back={()=>go('welcome')}><label>Your name</label><input value={name} onChange={e=>setName(e.target.value)}/><label>Creator type</label><div className="chips">{['Motorcycle','Travel','Food','Gaming','Fitness','Education','Lifestyle','Music'].map(x=><button className={niche===x?'chip active':'chip'} onClick={()=>setNiche(x)}>{x}</button>)}</div><label>Platforms</label><div className="chips">{['Instagram','YouTube','Facebook','Threads'].map(x=><span className="chip active">{x}</span>)}</div><Btn onClick={()=>go('dna')}>Continue →</Btn></Page>;
 if(s==='dna')return <Page title="Build your Creator DNA" back={()=>go('setup')}><div className="card"><b>{name}</b><p className="muted">{niche} creator</p><p>Tell Copilot how you want your content to feel. It will use this whenever it creates something for you.</p></div><label>Audience</label><input defaultValue="Motorcycle & adventure lovers"/><label>Style</label><textarea value={style} onChange={e=>setStyle(e.target.value)}/><div className="card"><b>AI remembers</b><p className="muted">Your niche • tone • language • editing preference • successful content</p></div><Btn onClick={()=>go('home')}>Save Creator DNA →</Btn></Page>;
 if(s==='home')return <Page title={`Good morning, ${name} 👋`} nav={nav}><div className="score"><div><span>Creator Intelligence</span><strong>82</strong><small>/100</small></div><span>↑ 12% this week</span></div><section><div className="sectionHead"><h2>What are we creating today?</h2></div><div className="card action" onClick={()=>go('create')}><b>✦ Create with AI</b><p>Turn an idea or your footage into a Reel.</p></div></section><h2>Recent content</h2><div className="grid"><div className="tile">🏔️<b>Ladakh Ride</b><small>12.4K views</small></div><div className="tile">🏍️<b>Dominar POV</b><small>8.7K views</small></div></div></Page>;
 if(s==='create')return <Page title="What are we creating?" back={()=>go('home')} nav={nav}><div className="option" onClick={()=>go('upload')}><span>🎬</span><div><b>Reel / Short</b><p>Turn footage into a social video.</p></div>→</div><div className="option"><span>💡</span><div><b>Idea</b><p>Generate content ideas for your niche.</p></div>→</div><div className="option"><span>✍️</span><div><b>Script</b><p>Build a hook, story and voiceover.</p></div>→</div></Page>;
 if(s==='upload')return <Page title="Add your footage" back={()=>go('create')}><div className="upload"><input type="file" accept="video/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="uploadIcon">＋</div><b>{file?file.name:'Choose videos from your iPhone'}</b><p className="muted">Files stay on this prototype device.</p></div><Btn onClick={()=>go('analysis')}>Analyze Footage →</Btn></Page>;
 if(s==='analysis')return <Page title="AI is studying your footage" back={()=>go('upload')}><div className="processing"><div className="spinner"/><h2>Analyzing clips…</h2><p>Finding strong moments, subjects, movement and story opportunities.</p></div><div className="card"><b>Detected</b><p>🏍️ Motorcycle • 🏔️ Mountains • 🛣️ Roads • 🌅 Golden hour</p></div><Btn onClick={()=>go('story')}>Continue →</Btn></Page>;
 if(s==='story')return <Page title="Choose your story" back={()=>go('analysis')}><p className="muted">Copilot found several ways to tell this story.</p>{['Cinematic','Adventure','Emotional','Energetic','Storytelling'].map((x,i)=><div className={i===0?'story selected':'story'} onClick={()=>go('instructions')}><b>{x}</b><span>{i===0?'Strong visual journey with natural pacing.':'Alternative direction for your footage.'} →</span></div>)}</Page>;
 if(s==='instructions')return <Page title="Tell AI what you want" back={()=>go('story')}><textarea className="big" defaultValue="Make it cinematic, emotional and natural. Start with the strongest mountain shot. Keep motorcycle engine sounds. Avoid excessive transitions."/><div className="chips"><span className="chip active">Natural</span><span className="chip active">30 sec</span><span className="chip active">Original audio</span></div><Btn onClick={()=>go('draft')}>Build my draft →</Btn></Page>;
 if(s==='draft')return <Page title="Your AI draft" back={()=>go('instructions')}><div className="video"><div className="play">▶</div><span>30 sec • 12 clips</span></div><div className="card"><b>Creator DNA match</b><strong className="percent">86%</strong><p className="muted">Natural pacing • cinematic tone • authentic engine sound</p></div><Btn onClick={()=>go('edit')}>Improve with AI →</Btn><Btn secondary onClick={()=>go('package')}>Looks good →</Btn></Page>;
 if(s==='edit')return <Page title="Tell AI what to change" back={()=>go('draft')}><div className="chat"><p><b>You:</b> Make the beginning more powerful and keep more engine sound.</p><p><b>Copilot:</b> Done. I strengthened the first 3 seconds and restored engine audio.</p></div>{['Stronger hook','More emotional','Remove slow sections','More engine sound'].map(x=><button className="quick" onClick={()=>setMsg('AI applied: '+x)}>✨ {x}</button>)}{msg&&<div className="success">✓ {msg}</div>}<Btn onClick={()=>go('package')}>Continue to packaging →</Btn></Page>;
 if(s==='package')return <Page title="Package your content" back={()=>go('edit')}><label>Caption</label><textarea defaultValue="Some roads take you somewhere. Others become a part of you. 🏔️🏍️"/><label>Hashtags</label><input defaultValue="#Ladakh #MotorcycleTravel #Adventure #MotoVlog #India"/><div className="chips"><span className="chip active">Instagram Reel</span><span className="chip active">YouTube Short</span><span className="chip active">Facebook Reel</span></div><Btn onClick={()=>go('publish')}>Prepare to publish →</Btn></Page>;
 if(s==='publish')return <Page title="Ready to publish" back={()=>go('package')}><div className="success bigsuccess">✓ Your content is ready</div><div className="card"><b>3 platform versions prepared</b><p className="muted">Instagram Reel • YouTube Short • Facebook Reel</p></div><Btn onClick={()=>go('insights')}>Publish & see insights →</Btn></Page>;
 if(s==='insights')return <Page title="Creator Insights" nav={nav}><div className="metrics"><div><b>12.4K</b><small>Views</small></div><div><b>8.7%</b><small>Engagement</small></div><div><b>74%</b><small>Watch rate</small></div></div><div className="card"><b>✦ AI read</b><p>Your strongest content uses mountain reveals in the first 3 seconds and authentic riding audio. Keep building around that.</p></div><h2>Next ideas</h2>{['POV: The road to Umling La','What nobody tells you about Ladakh rides','3 things I learned riding 1,000 km'].map(x=><div className="idea">💡 {x}</div>)}</Page>;
 return null;
}
function Page({title,children,back,nav}){return <main className="app"><header>{back&&<button className="back" onClick={back}>‹</button>}<h1>{title}</h1></header><div className="content">{children}</div>{nav}</main>}
createRoot(document.getElementById('root')).render(<App/>);
